backend:
  name: git-gateway
  branch: main # your default branch

media_folder: "assets/images" # Uploaded files go here in repo
public_folder: "/assets/images" # URL path used on site

collections:
  - name: "today"
    label: "Today"
    folder: "src/today"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Due Date", name: "due_date", widget: "datetime" }

  - name: "urgent"
    label: "Urgent Notices"
    folder: "src/urgent"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Due Date", name: "due_date", widget: "datetime" }

  - name: "normal"
    label: "Notices"
    folder: "src/normal"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Due Date", name: "due_date", widget: "datetime" }

  - name: "opportunities"
    label: "Opportunities"
    folder: "src/opportunities"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Due Date", name: "due_date", widget: "datetime" }
      - { label: "Permanent", name: "permanent", widget: "boolean" }

  - name: "community"
    label: "Community"
    folder: "src/community"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Due Date", name: "due_date", widget: "datetime" }
      - { label: "Approved", name: "approved", widget: "boolean" }

  - name: "past"
    label: "Past Notices"
    folder: "src/past"
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Due Date", name: "due_date", widget: "datetime" }
