backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Notices & Opportunities"
    folder: "src/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date created", name: "date", widget: "datetime" }
      - { label: "Due date", name: "due_date", widget: "datetime", required: true }
      - { label: "Section", name: "section", widget: "select", options: ["normal", "urgent", "community", "opportunity"], default: "normal" }
      - { label: "Permanent", name: "permanent", widget: "boolean", default: false }
      - { label: "Published", name: "published", widget: "boolean", default: false }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }